# Generated by Django 6.0.8 on 2026-10-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_historicalorderpayment_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderpayment',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual (staff confirmed)'), ('stripe', 'Stripe'), ('xcash', 'XCash (crypto)')], db_index=True, default='manual', max_length=20, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentattempt',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual (staff confirmed)'), ('stripe', 'Stripe'), ('xcash', 'XCash (crypto)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpaymentmethod',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual (staff confirmed)'), ('stripe', 'Stripe'), ('xcash', 'XCash (crypto)')], db_index=True, default='manual', help_text='Gateway that processes this method.', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual (staff confirmed)'), ('stripe', 'Stripe'), ('xcash', 'XCash (crypto)')], db_index=True, default='manual', max_length=20, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual (staff confirmed)'), ('stripe', 'Stripe'), ('xcash', 'XCash (crypto)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual (staff confirmed)'), ('stripe', 'Stripe'), ('xcash', 'XCash (crypto)')], db_index=True, default='manual', help_text='Gateway that processes this method.', max_length=20),
        ),
    ]
