#
# General
#

namespace: shkeeper
external_ip: 0.0.0.0
domain: ""
additional_domains: []

storageClassName: hostpath

#
# ShKeeper
#

shkeeper:
  image: vsyshost/shkeeper:2.5.32
  port: 5000
  enable_payout_callback: false

#
# BTC
#

btc:
  enabled: false

#
# Litecoin
#

ltc:
  enabled: false

#
# Dogecoin
#

doge:
  enabled: false

#
# Firo
#

firo:
  enabled: false

#
# Tron
#

#tron_fullnode:
#  image: vsyshost/javatron:GreatVoyage-v4.8.2.3
#  enabled: false
#  url: http://fullnode.tron.shkeeper.io
#  solidity_url: http://fullnode.tron.shkeeper.io
#  mainnet: true

tron_fullnode:
  enabled: false
  mainnet: false
  url: https://nile.trongrid.io/

tron_shkeeper:
  image: vsyshost/tron-shkeeper:2.0.0
  host: tron-shkeeper
  port: 6000

trx:
  enabled: true

usdt:
  enabled: true

usdc:
  enabled: false

#
# Ethereum
#

eth:
  enabled: false
eth_usdt:
  enabled: false
eth_usdc:
  enabled: false
eth_pyusd:
  enabled: false
eth_dai:
  enabled: false

#
# Monero
#

monero:
  enabled: false

#
# BNB
#

bnb:
  enabled: false
bnb_usdt:
  enabled: false
bnb_usdc:
  enabled: false

#
# XRP
#

xrp:
  enabled: false

#
# Polygon
#

matic:
  enabled: false
polygon_usdt:
  enabled: false
polygon_usdc:
  enabled: false

#
# Avalanche
#

avax:
  enabled: false
avalanche_usdt:
  enabled: false
avalanche_usdc:
  enabled: false

#
# BTC Lightning
#

btc_lightning:
  enabled: false

#
# Solana
#

sol:
  enabled: false
solana_usdt:
  enabled: false
solana_usdc:
  enabled: false
solana_pyusd:
  enabled: false

#
# Arbitrum
#

arbeth:
  enabled: false
arb_token:
  enabled: false
arb_usdc:
  enabled: false
arb_pyusd:
  enabled: false

#
# Optimism
#

opeth:
  enabled: false
op_token:
  enabled: false
op_usdc:
  enabled: false
op_usdt:
  enabled: false

#
# TON
#

ton:
  enabled: false
ton_usdt:
  enabled: false

#
# AML
#

aml:
  enabled: false